name: Test

on: [push, pull_request]

jobs:
  test-deploy:
    name: Test able to deploy to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: npm ci

      - name: Compile
        run: npm run build

      - name: Pushlish test
        run: npm publish --dry-run
